baseURL = "https://audacious.blog/"
languageCode = "en-us"
titleCaseStyle = "AP"

title = "Audacious"
uglyurls = false
publishDir = "docs"
disableKinds = ['RSS', 'taxonomy', 'taxonomyTerm']
[permalinks]
	notes = "/:year/:filename"
	essays = "/:year/:filename"
	pages = "/:filename"

[sitemap]
  changefreq = 'monthly'
  priority = 0.5
  filename = 'sitemap.xml'

[author]
  name = 'K.Q. Dreger'
  url = 'https://twitter.com/dreger'

[params]
  icon = '&#9650;&#65038;'


[mediaTypes]
  [mediaTypes."application/xml"]
    suffixes = ["xml"]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats.Json]
  mediaType = "application/json"
  baseName = "feeds/main"
  isPlainText = true

[outputFormats.Xml]
  mediaType = "application/xml"
  baseName = "feeds/main"
  isPlainText = true

[outputs]
  home = [ "HTML", "Xml", "Json" ]